--- #YAML:1.0
name:                Bundle-POE-All
version:             1.03
abstract:            Installs all the modules in the POE::* namespace
license:             perl
author:              
    - Apocalypse <APOCAL@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    CPANPLUS:                      0.051
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
